_target_: boltzgen.task.predict.predict.Predict

debug: false

data:
  _target_: boltzgen.task.predict.data_from_generated.FromGeneratedDataModule
  cfg:
    _target_: boltzgen.task.predict.data_from_generated.DataConfig
    tokenizer:
      _target_: boltzgen.data.tokenize.tokenizer.Tokenizer
      atomize_modified_residues: false
    featurizer:
      _target_: boltzgen.data.feature.featurizer.Featurizer

    suffix: .cif
    suffix_metadata: .npz
    suffix_native: _native.cif
    samples_per_target: 1000000000000000
    num_targets: 10000000000000
    moldir: null

    batch_size: 1
    num_workers: 4
    pin_memory: true
    disulfide_prob: 1.0
    disulfide_on: true
  design_dir: null
  target_templates: true
  return_native: false
  fail_if_no_designs: true
  output_dir: null
  
keys_dict_out: ["min_interaction_pae", "min_design_to_target_pae", "interaction_pae", "ligand_iptm", "protein_iptm", "iptm", "design_iptm", "design_iiptm", "design_to_target_iptm", "design_ptm", "target_ptm", "ptm"]

writer:
  _target_: boltzgen.task.predict.writer.FoldingWriter
  design_dir: ${data.design_dir}

trainer:
  accelerator: gpu
  logger: false
  devices: 1
  precision: bf16-mixed

name: null
output: null
checkpoint: null
matmul_precision: null
recycling_steps: 3
sampling_steps: 200
diffusion_samples: 5

override:
  validators: null