_target_: boltzgen.task.predict.predict.Predict

data:
  _target_: boltzgen.task.predict.data_from_yaml.FromYamlDataModule
  cfg:
    _target_: boltzgen.task.predict.data_from_yaml.DataConfig
    tokenizer:
      _target_: boltzgen.data.tokenize.tokenizer.Tokenizer
      atomize_modified_residues: false
    featurizer:
      _target_: boltzgen.data.feature.featurizer.Featurizer
    moldir: null
    yaml_path: null
    output_dir: ${output}
    diffusion_samples: ${diffusion_samples}

    # Design
    backbone_only: false
    atom14: true
    atom37: false
    disulfide_prob: 1.0
    disulfide_on: true
  batch_size: 1
  num_workers: 4
  pin_memory: true
  

writer:
  _target_: boltzgen.task.predict.writer.DesignWriter
  output_dir: ${output}
  res_atoms_only: false
  atom14: ${data.cfg.atom14}
  atom37: ${data.cfg.atom37}
  backbone_only: ${data.cfg.backbone_only}
  write_native: false

trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed

name: null
output: null
checkpoint: null
matmul_precision: high
recycling_steps: 3
sampling_steps: 500
diffusion_samples: 1
compile_pairformer: false
compile_structure: false

override:
  masker_args:
    mask: true
    mask_backbone: false

  validators: null

  step_scale_schedule:
    - step_scale: 1.8
      period: 0.25
    - step_scale: 2.0
      period: 0.25
    - step_scale: 1.8
      period: 0.25
    - step_scale: 2.0
      period: 0.25

  noise_scale_schedule:
    - noise_scale: 0.95
      period: 0.25
    - noise_scale: 0.88
      period: 0.25
    - noise_scale: 0.95
      period: 0.25
    - noise_scale: 0.88
      period: 0.25

  diffusion_process_args:
    sigma_min: 0.0004  # min noise level
    sigma_max: 160.0  # max noise level
    sigma_data: 16.0  # standard deviation of data distribution
    rho: 7  # controls the sampling schedule
    P_mean: -1.2  # mean of log-normal distribution from which noise is drawn for training
    P_std: 1.5  # standard deviation of log-normal distribution from which noise is drawn for training
    gamma_0: 0.8
    gamma_min: 1.0
    noise_scale: null
    step_scale: null
    mse_rotational_alignment: true
    coordinate_augmentation: true
    alignment_reverse_diff: true
    synchronize_sigmas: false
    sampling_schedule: "dilated"
    time_dilation: 2.667 
    time_dilation_start: 0.6 
    time_dilation_end: 0.8
    

